using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Text;
using Microsoft.VisualBasic;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.Processing;
//using System.Web.Helpers;

namespace Intranet.API.Helpers.Extensions
{
    public static class FileExtensions
    {
    }
}


public static class FileContent
{
    public static byte[] ResizeImage(this byte[] data, int width = 80, int height = 80, string tipo = ".jpg")
    {
        byte[] result = null;

        try
        {
            using MemoryStream inStream = new(data);

            try
            {

                using MemoryStream outStream =  new();

                IImageFormat format;

                using (var image = Image.Load(inStream, out format))
                {

                    if ((width < image.Width || height < image.Height))
                    {
                        image.Mutate(x => x.Resize(width, height));
                    }

                    image.SaveAsJpeg(outStream);
                }

                result = outStream.GetBuffer();

            }
            catch (Exception e)
            {

                Console.WriteLine(e.Message);

                throw;

            }
        }
        catch 
        {
            result = data;
        }

        return result;
    }

    public static bool IsImageExtension(this string nomeArquivo)
    {
        var extension = Path.GetExtension(nomeArquivo).ToLower();

        var _validExtensions = new[] { ".tiff", ".bmp", ".jpeg", ".gif", ".png", ".jpg" };

        return _validExtensions.Contains(extension);
    }

    public static bool IsVideoExtension(this string nomeArquivo)
    {
        var extension = Path.GetExtension(nomeArquivo).ToLower();

        var _validExtensions = new[] { ".aaf", ".3gp", ".asf", ".avi", ".flv", ".wmv", ".mpg", ".mpeg", ".mpe", ".mp4" };

        return _validExtensions.Contains(extension);
    }

    // public static bool IsDigitsOnly(this string str)
    // {
    //     foreach (var c in str)
    //     {
    //         if (c < "0" || c > "9")
    //             return false;
    //     }

    //     return true;
    // }


    public static string GetMIMEtype(this string nomeArquivo)
    {
        var result = string.Empty;

        if (string.IsNullOrEmpty(nomeArquivo))
            nomeArquivo = string.Empty;
        // No momento estamos usando apenas a lista resumida. Deixei a lista completa aqui para eventuais referências futuras... Caron 06/07/2013

        // origem dessa lista: http://www.freeformatter.com/mime-types-list.html

        var lista = GetList();

        var extension = Path.GetExtension(nomeArquivo.ToLower());

        if (lista.ContainsKey(extension))
            result = lista[extension];
        else
            result = lista[".txt"];

        return result;
    }

    private static Dictionary<string, string> GetList()
    {
        return new Dictionary<string, string>()
        {
            {".bin", "application/octet-stream"},
            {".cww", "application/prs.cww"},
            {".rif", "application/reginfo+xml"},
            {".cod", "application/vnd.rim.cod"},
            {".rm", "application/vnd.rn-realmedia"},
            {".sdc", "application/vnd.stardivision.calc"},
            {".sda", "application/vnd.stardivision.draw"},
            {".sdd", "application/vnd.stardivision.impress"},
            {".smf", "application/vnd.stardivision.math"},
            {".sdw", "application/vnd.stardivision.writer"},
            {".sgl", "application/vnd.stardivision.writer-global"},
            {".ras", "image/x-cmu-raster"},
            {".plb", "application/vnd.3gpp.pic-bw-large"},
            {".psb", "application/vnd.3gpp.pic-bw-small"},
            {".pvb", "application/vnd.3gpp.pic-bw-var"},
            {".tcap", "application/vnd.3gpp2.tcap"},
            {".pdf", "application/pdf"},
            {".air", "application/vnd.adobe.air-application-installer-package+zip"},
            {".cdx", "chemical/x-cdx"},
            {".cpt", "application/mac-compactpro"},
            {".cif", "chemical/x-cif"},
            {".cmdf", "chemical/x-cmdf"},
            {".curl", "text/vnd.curl"},
            {".dcurl", "text/vnd.curl.dcurl"},
            {".mcurl", "text/vnd.curl.mcurl"},
            {".scurl", "text/vnd.curl.scurl"},
            {".res", "application/x-dtbresource+xml"},
            {".es", "application/ecmascript"},
            {".exi", "application/exi"},
            {".emma", "application/emma+xml"},
            {".fli", "video/x-fli"},
            {".gtar", "application/x-gtar"},
            {"N/A", "application/andrew-inset"},
            {".stk", "application/hyperstudio"},
            {".ma", "application/mathematica"},
            {".x3d", "application/vnd.hzn-3d-crossword"},
            {".mseq", "application/vnd.mseq"},
            {".pwn", "application/vnd.3m.post-it-notes"},
            {".acc", "application/vnd.americandynamics.acc"},
            {".acu", "application/vnd.acucobol"},
            {".atc", "application/vnd.acucorp"},
            {".fxp", "application/vnd.adobe.fxp"},
            {".ahead", "application/vnd.ahead.space"},
            {".azf", "application/vnd.airzip.filesecure.azf"},
            {".azs", "application/vnd.airzip.filesecure.azs"},
            {".ami", "application/vnd.amiga.ami"},
            {".cii", "application/vnd.anser-web-certificate-issue-initiation"},
            {".fti", "application/vnd.anser-web-funds-transfer-initiation"},
            {".atx", "application/vnd.antix.game-component"},
            {".mpkg", "application/vnd.apple.installer+xml"},
            {".les", "application/vnd.hhe.lesson-player"},
            {".swi", "application/vnd.aristanetworks.swi"},
            {".aep", "application/vnd.audiograph"},
            {".bmi", "application/vnd.bmi"},
            {".btif", "image/prs.btif"},
            {".rep", "application/vnd.businessobjects"},
            {".c11amc", "application/vnd.cluetrust.cartomobile-config"},
            {".c11amz", "application/vnd.cluetrust.cartomobile-config-pkg"},
            {".cdxml", "application/vnd.chemdraw+xml"},
            {".mmd", "application/vnd.chipnuts.karaoke-mmd"},
            {".cdbcmsg", "application/vnd.contact.cmsg"},
            {".cdy", "application/vnd.cinderella"},
            {".cla", "application/vnd.claymore"},
            {".clkx", "application/vnd.crick.clicker"},
            {".clkk", "application/vnd.crick.clicker.keyboard"},
            {".clkp", "application/vnd.crick.clicker.palette"},
            {".clkt", "application/vnd.crick.clicker.template"},
            {".clkw", "application/vnd.crick.clicker.wordbank"},
            {".c4g", "application/vnd.clonk.c4group"},
            {".dae", "model/vnd.collada+xml"},
            {".csp", "application/vnd.commonspace"},
            {".xar", "application/vnd.xara"},
            {".cmc", "application/vnd.cosmocaller"},
            {".wbs", "application/vnd.criticaltools.wbs+xml"},
            {".cryptonote", "application/vnd.rig.cryptonote"},
            {".ppd", "application/vnd.cups-ppd"},
            {".car", "application/vnd.curl.car"},
            {".pcurl", "application/vnd.curl.pcurl"},
            {".cmp", "application/vnd.yellowriver-custom-menu"},
            {".rdz", "application/vnd.data-vision.rdz"},
            {".uva", "audio/vnd.dece.audio"},
            {".uvi", "image/vnd.dece.graphic"},
            {".uvh", "video/vnd.dece.hd"},
            {".uvm", "video/vnd.dece.mobile"},
            {".uvu", "video/vnd.uvvu.mp4"},
            {".uvp", "video/vnd.dece.pd"},
            {".uvs", "video/vnd.dece.sd"},
            {".uvv", "video/vnd.dece.video"},
            {".ait", "application/vnd.dvb.ait"},
            {".svc", "application/vnd.dvb.service"},
            {".eol", "audio/vnd.digital-winds"},
            {".xdw", "application/vnd.fujixerox.docuworks"},
            {".xbd", "application/vnd.fujixerox.docuworks.binder"},
            {".mlp", "application/vnd.dolby.mlp"},
            {".dpg", "application/vnd.dpgraph"},
            {".dra", "audio/vnd.dra"},
            {".dfac", "application/vnd.dreamfactory"},
            {".dts", "audio/vnd.dts"},
            {".dtshd", "audio/vnd.dts.hd"},
            {".geo", "application/vnd.dynageo"},
            {".ecelp4800", "audio/vnd.nuera.ecelp4800"},
            {".ecelp7470", "audio/vnd.nuera.ecelp7470"},
            {".ecelp9600", "audio/vnd.nuera.ecelp9600"},
            {".mag", "application/vnd.ecowin.chart"},
            {".mmr", "image/vnd.fujixerox.edmics-mmr"},
            {".rlc", "image/vnd.fujixerox.edmics-rlc"},
            {".mgz", "application/vnd.proteus.magazine"},
            {".sc", "application/vnd.ibm.secure-container"},
            {".nml", "application/vnd.enliven"},
            {".xpr", "application/vnd.is-xpr"},
            {".xfdl", "application/vnd.xfdl"},
            {".ez2", "application/vnd.ezpix-album"},
            {".ez3", "application/vnd.ezpix-package"},
            {".fst", "image/vnd.fst"},
            {".fbs", "image/vnd.fastbidsheet"},
            {".fe_launch", "application/vnd.denovo.fcselayout-link"},
            {".flx", "text/vnd.fmi.flexstor"},
            {".gph", "application/vnd.flographit"},
            {".ftc", "application/vnd.fluxtime.clip"},
            {".fly", "text/vnd.fly"},
            {".fdf", "application/vnd.fdf"},
            {".fpx", "image/vnd.fpx"},
            {".npx", "image/vnd.net-fpx"},
            {".fm", "application/vnd.framemaker"},
            {".mif", "application/vnd.mif"},
            {".fsc", "application/vnd.fsc.weblaunch"},
            {".fnc", "application/vnd.frogans.fnc"},
            {".ltf", "application/vnd.frogans.ltf"},
            {".ddd", "application/vnd.fujixerox.ddd"},
            {".oas", "application/vnd.fujitsu.oasys"},
            {".oa2", "application/vnd.fujitsu.oasys2"},
            {".oa3", "application/vnd.fujitsu.oasys3"},
            {".fg5", "application/vnd.fujitsu.oasysgp"},
            {".bh2", "application/vnd.fujitsu.oasysprs"},
            {".fzs", "application/vnd.fuzzysheet"},
            {".fvt", "video/vnd.fvt"},
            {".gmx", "application/vnd.gmx"},
            {".gdl", "model/vnd.gdl"},
            {".txd", "application/vnd.genomatix.tuxedo"},
            {".ggb", "application/vnd.geogebra.file"},
            {".ggt", "application/vnd.geogebra.tool"},
            {".gex", "application/vnd.geometry-explorer"},
            {".gxt", "application/vnd.geonext"},
            {".g2w", "application/vnd.geoplan"},
            {".g3w", "application/vnd.geospace"},
            {".kml", "application/vnd.google-earth.kml+xml"},
            {".kmz", "application/vnd.google-earth.kmz"},
            {".gqf", "application/vnd.grafeq"},
            {".gv", "text/vnd.graphviz"},
            {".gac", "application/vnd.groove-account"},
            {".ghf", "application/vnd.groove-help"},
            {".gim", "application/vnd.groove-identity-message"},
            {".grv", "application/vnd.groove-injector"},
            {".gtm", "application/vnd.groove-tool-message"},
            {".tpl", "application/vnd.groove-tool-template"},
            {".vcg", "application/vnd.groove-vcard"},
            {".gtw", "model/vnd.gtw"},
            {".hal", "application/vnd.hal+xml"},
            {".hbci", "application/vnd.hbci"},
            {".hpid", "application/vnd.hp-hpid"},
            {".hps", "application/vnd.hp-hps"},
            {".rip", "audio/vnd.rip"},
            {".jlt", "application/vnd.hp-jlyt"},
            {".pclxl", "application/vnd.hp-pclxl"},
            {".pcl", "application/vnd.hp-pcl"},
            {".hpgl", "application/vnd.hp-hpgl"},
            {".hvs", "application/vnd.yamaha.hv-script"},
            {".hvd", "application/vnd.yamaha.hv-dic"},
            {".hvp", "application/vnd.yamaha.hv-voice"},
            {".sfd-hdstx", "application/vnd.hydrostatix.sof-data"},
            {".irm", "application/vnd.ibm.rights-management"},
            {".icc", "application/vnd.iccprofile"},
            {".igl", "application/vnd.igloader"},
            {".ivp", "application/vnd.immervision-ivp"},
            {".ivu", "application/vnd.immervision-ivu"},
            {".3dml", "text/vnd.in3d.3dml"},
            {".spot", "text/vnd.in3d.spot"},
            {".i2g", "application/vnd.intergeo"},
            {".xpw", "application/vnd.intercon.formnet"},
            {".fcs", "application/vnd.isac.fcs"},
            {".igm", "application/vnd.insors.igm"},
            {".rcprofile", "application/vnd.ipunplugged.rcprofile"},
            {".irp", "application/vnd.irepository.package+xml"},
            {".jad", "text/vnd.sun.j2me.app-descriptor"},
            {".joda", "application/vnd.joost.joda-archive"},
            {".jpm", "video/jpm"},
            {".ktz", "application/vnd.kahootz"},
            {".karbon", "application/vnd.kde.karbon"},
            {".chrt", "application/vnd.kde.kchart"},
            {".kfo", "application/vnd.kde.kformula"},
            {".flw", "application/vnd.kde.kivio"},
            {".kon", "application/vnd.kde.kontour"},
            {".kpr", "application/vnd.kde.kpresenter"},
            {".ksp", "application/vnd.kde.kspread"},
            {".kwd", "application/vnd.kde.kword"},
            {".htke", "application/vnd.kenameaapp"},
            {".kia", "application/vnd.kidspiration"},
            {".kne", "application/vnd.kinar"},
            {".sse", "application/vnd.kodak-descriptor"},
            {".lasxml", "application/vnd.las.las+xml"},
            {".lbd", "application/vnd.llamagraphics.life-balance.desktop"},
            {".lbe", "application/vnd.llamagraphics.life-balance.exchange+xml"},
            {".jam", "application/vnd.jam"},
            {".123", "application/vnd.lotus-1-2-3"},
            {".apr", "application/vnd.lotus-approach"},
            {".pre", "application/vnd.lotus-freelance"},
            {".nsf", "application/vnd.lotus-notes"},
            {".org", "application/vnd.lotus-organizer"},
            {".scm", "application/vnd.lotus-screencam"},
            {".lwp", "application/vnd.lotus-wordpro"},
            {".lvp", "audio/vnd.lucent.voice"},
            {".portpkg", "application/vnd.macports.portpkg"},
            {".mgp", "application/vnd.osgeo.mapguide.package"},
            {".nbp", "application/vnd.wolfram.player"},
            {".mc1", "application/vnd.medcalcdata"},
            {".cdkey", "application/vnd.mediastation.cdkey"},
            {".mwf", "application/vnd.mfer"},
            {".mfm", "application/vnd.mfmp"},
            {".mcd", "application/vnd.mcd"},
            {".flo", "application/vnd.micrografx.flo"},
            {".igx", "application/vnd.micrografx.igx"},
            {".es3", "application/vnd.eszigno3+xml"},
            {".pya", "audio/vnd.ms-playready.media.pya"},
            {".pyv", "video/vnd.ms-playready.media.pyv"},
            {".mpy", "application/vnd.ibm.minipay"},
            {".mj2", "video/mj2"},
            {".afp", "application/vnd.ibm.modcap"},
            {".rms", "application/vnd.jcp.javame.midlet-rms"},
            {".tmo", "application/vnd.tmobile-livetv"},
            {".daf", "application/vnd.mobius.daf"},
            {".dis", "application/vnd.mobius.dis"},
            {".mbk", "application/vnd.mobius.mbk"},
            {".mqy", "application/vnd.mobius.mqy"},
            {".msl", "application/vnd.mobius.msl"},
            {".plc", "application/vnd.mobius.plc"},
            {".txf", "application/vnd.mobius.txf"},
            {".mpc", "application/vnd.mophun.certificate"},
            {".mpn", "application/vnd.mophun.application"},
            {".mxu", "video/vnd.mpegurl"},
            {".cil", "application/vnd.ms-artgalry"},
            {".cab", "application/vnd.ms-cab-compressed"},
            {".ims", "application/vnd.ms-ims"},
            {".eot", "application/vnd.ms-fontobject"},
            {".xls", "application/vnd.ms-excel"},
            {".xlam", "application/vnd.ms-excel.addin.macroenabled.12"},
            {".xlsb", "application/vnd.ms-excel.sheet.binary.macroenabled.12"},
            {".xlsm", "application/vnd.ms-excel.sheet.macroenabled.12"},
            {".xltm", "application/vnd.ms-excel.template.macroenabled.12"},
            {".lrm", "application/vnd.ms-lrm"},
            {".thmx", "application/vnd.ms-officetheme"},
            {".ppt", "application/vnd.ms-powerpoint"},
            {".ppam", "application/vnd.ms-powerpoint.addin.macroenabled.12"},
            {".pptm", "application/vnd.ms-powerpoint.presentation.macroenabled.12"},
            {".sldm", "application/vnd.ms-powerpoint.slide.macroenabled.12"},
            {".ppsm", "application/vnd.ms-powerpoint.slideshow.macroenabled.12"},
            {".potm", "application/vnd.ms-powerpoint.template.macroenabled.12"},
            {".mpp", "application/vnd.ms-project"},
            {".cat", "application/vnd.ms-pki.seccat"},
            {".stl", "application/vnd.ms-pki.stl"},
            {".wpl", "application/vnd.ms-wpl"},
            {".docm", "application/vnd.ms-word.document.macroenabled.12"},
            {".dotm", "application/vnd.ms-word.template.macroenabled.12"},
            {".wps", "application/vnd.ms-works"},
            {".xps", "application/vnd.ms-xpsdocument"},
            {".mts", "model/vnd.mts"},
            {".mpm", "application/vnd.blueice.multipass"},
            {".mus", "application/vnd.musician"},
            {".msty", "application/vnd.muvee.style"},
            {".ngdat", "application/vnd.nokia.n-gage.data"},
            {".n-gage", "application/vnd.nokia.n-gage.symbian.install"},
            {".nlu", "application/vnd.neurolanguage.nlu"},
            {".dna", "application/vnd.dna"},
            {".nnd", "application/vnd.noblenet-directory"},
            {".nns", "application/vnd.noblenet-sealer"},
            {".nnw", "application/vnd.noblenet-web"},
            {".rpst", "application/vnd.nokia.radio-preset"},
            {".rpss", "application/vnd.nokia.radio-presets"},
            {".edm", "application/vnd.novadigm.edm"},
            {".edx", "application/vnd.novadigm.edx"},
            {".ext", "application/vnd.novadigm.ext"},
            {".dd2", "application/vnd.oma.dd2+xml"},
            {".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
            {".sldx", "application/vnd.openxmlformats-officedocument.presentationml.slide"},
            {".ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow"},
            {".potx", "application/vnd.openxmlformats-officedocument.presentationml.template"},
            {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
            {".xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
            {".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
            {".dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template"},
            {".qbo", "application/vnd.intu.qbo"},
            {".oxt", "application/vnd.openofficeorg.extension"},
            {".osf", "application/vnd.yamaha.openscoreformat"},
            {".odc", "application/vnd.oasis.opendocument.chart"},
            {".otc", "application/vnd.oasis.opendocument.chart-template"},
            {".odb", "application/vnd.oasis.opendocument.database"},
            {".odf", "application/vnd.oasis.opendocument.formula"},
            {".odft", "application/vnd.oasis.opendocument.formula-template"},
            {".odg", "application/vnd.oasis.opendocument.graphics"},
            {".otg", "application/vnd.oasis.opendocument.graphics-template"},
            {".odi", "application/vnd.oasis.opendocument.image"},
            {".oti", "application/vnd.oasis.opendocument.image-template"},
            {".odp", "application/vnd.oasis.opendocument.presentation"},
            {".otp", "application/vnd.oasis.opendocument.presentation-template"},
            {".ods", "application/vnd.oasis.opendocument.spreadsheet"},
            {".ots", "application/vnd.oasis.opendocument.spreadsheet-template"},
            {".odt", "application/vnd.oasis.opendocument.text"},
            {".odm", "application/vnd.oasis.opendocument.text-master"},
            {".ott", "application/vnd.oasis.opendocument.text-template"},
            {".oth", "application/vnd.oasis.opendocument.text-web"},
            {".osfpvg", "application/vnd.yamaha.openscoreformat.osfpvg+xml"},
            {".dp", "application/vnd.osgi.dp"},
            {".pdb", "application/vnd.palm"},
            {".paw", "application/vnd.pawaafile"},
            {".efif", "application/vnd.picsel"},
            {".plf", "application/vnd.pocketlearn"},
            {".pml", "application/vnd.ctc-posml"},
            {".pbd", "application/vnd.powerbuilder6"},
            {".box", "application/vnd.previewsystems.box"},
            {".ptid", "application/vnd.pvi.ptid1"},
            {".str", "application/vnd.pg.format"},
            {".ei6", "application/vnd.pg.osasli"},
            {".dsc", "text/prs.lines.tag"},
            {".qps", "application/vnd.publishare-delta-tree"},
            {".wg", "application/vnd.pmi.widget"},
            {".qxd", "application/vnd.quark.quarkxpress"},
            {".esf", "application/vnd.epson.esf"},
            {".msf", "application/vnd.epson.msf"},
            {".ssf", "application/vnd.epson.ssf"},
            {".qam", "application/vnd.epson.quickanime"},
            {".qfx", "application/vnd.intu.qfx"},
            {".bed", "application/vnd.realvnc.bed"},
            {".mxl", "application/vnd.recordare.musicxml"},
            {".musicxml", "application/vnd.recordare.musicxml+xml"},
            {".rp9", "application/vnd.cloanto.rp9"},
            {".jisp", "application/vnd.jisp"},
            {".link66", "application/vnd.route66.link66+xml"},
            {".st", "application/vnd.sailingtracker.track"},
            {".sus", "application/vnd.sus-calendar"},
            {".sema", "application/vnd.sema"},
            {".semd", "application/vnd.semd"},
            {".semf", "application/vnd.semf"},
            {".seed", "application/vnd.fdsn.seed"},
            {".see", "application/vnd.seemail"},
            {".setpay", "application/set-payment-initiation"},
            {".setreg", "application/set-registration-initiation"},
            {".ifm", "application/vnd.shana.informed.formdata"},
            {".itp", "application/vnd.shana.informed.formtemplate"},
            {".iif", "application/vnd.shana.informed.interchange"},
            {".ipk", "application/vnd.shana.informed.package"},
            {".slt", "application/vnd.epson.salt"},
            {".aso", "application/vnd.accpac.simply.aso"},
            {".imp", "application/vnd.accpac.simply.imp"},
            {".twd", "application/vnd.simtech-mindmapper"},
            {".saf", "application/vnd.yamaha.smaf-audio"},
            {".mmf", "application/vnd.smaf"},
            {".spf", "application/vnd.yamaha.smaf-phrase"},
            {".teacher", "application/vnd.smart.teacher"},
            {".svd", "application/vnd.svd"},
            {".skp", "application/vnd.koan"},
            {".sm", "application/vnd.stepmania.stepchart"},
            {".sdkm", "application/vnd.solent.sdkm+xml"},
            {".xo", "application/vnd.olpc-sugar"},
            {".wqd", "application/vnd.wqd"},
            {".sis", "application/vnd.symbian.install"},
            {".xsm", "application/vnd.syncml+xml"},
            {".bdm", "application/vnd.syncml.dm+wbxml"},
            {".xdm", "application/vnd.syncml.dm+xml"},
            {".tao", "application/vnd.tao.intent-module-archive"},
            {".dxp", "application/vnd.spotfire.dxp"},
            {".sfs", "application/vnd.spotfire.sfs"},
            {".tpt", "application/vnd.trid.tpt"},
            {".mxs", "application/vnd.triscape.mxs"},
            {".tra", "application/vnd.trueapp"},
            {".umj", "application/vnd.umajin"},
            {".unityweb", "application/vnd.unity"},
            {".ufd", "application/vnd.ufdl"},
            {".uoml", "application/vnd.uoml+xml"},
            {".utz", "application/vnd.uiq.theme"},
            {".vsf", "application/vnd.vsf"},
            {".vcx", "application/vnd.vcx"},
            {".vsd", "application/vnd.visio"},
            {".vis", "application/vnd.visionary"},
            {".viv", "video/vnd.vivo"},
            {".vtu", "model/vnd.vtu"},
            {".wbmp", "image/vnd.wap.wbmp"},
            {".wbxml", "application/vnd.wap.wbxml"},
            {".wtb", "application/vnd.webturbo"},
            {".wmlc", "application/vnd.wap.wmlc"},
            {".wmlsc", "application/vnd.wap.wmlscriptc"},
            {".wpd", "application/vnd.wordperfect"},
            {".stf", "application/vnd.wt.stf"},
            {".xif", "image/vnd.xiff"},
            {".xul", "application/vnd.mozilla.xul+xml"},
            {".zir", "application/vnd.zul"},
            {".zmm", "application/vnd.handheld-entertainment+xml"},
            {".zaz", "application/vnd.zzazz.deck+xml"},
            {".chm", "application/vnd.ms-htmlhelp"},
            {".ser", "application/java-serialized-object"},
            {".js", "application/javascript"},
            {".azw", "application/vnd.amazon.ebook"},
            {".ktx", "image/ktx"},
            {".hqx", "application/mac-binhex40"},
            {".onetoc", "application/onenote"},
            {".otf", "application/x-font-otf"},
            {".par", "text/plain-bas"},
            {".psf", "application/x-font-linux-psf"},
            {".rnc", "application/relax-ng-compact-syntax"},
            {".ief", "image/ief"},
            {".jpeg", "image/jpeg"},
            {".jpg", "image/jpeg"},
            {"", "application/pgp-encrypted"},
            {".pgp", "application/pgp-signature"},
            {".msh", "model/mesh"},
            {".png", "image/png"},
            {".oda", "application/oda"},
            {".mrc", "application/marc"},
            {".p7m", "application/pkcs7-mime"},
            {".p7s", "application/pkcs7-signature"},
            {".sdp", "application/sdp"},
            {".uri", "text/uri-list"},
            {".cer", "application/pkix-cert"},
            {".crl", "application/pkix-crl"},
            {".pkipath", "application/pkix-pkipath"},
            {".pki", "application/pkixcmp"},
            {".eml", "message/rfc822"},
            {".p10", "application/pkcs10"},
            {".p12", "application/x-pkcs12"},
            {".p7b", "application/x-pkcs7-certificates"},
            {".p7r", "application/x-pkcs7-certreqresp"},
            {".pfr", "application/font-tdpfr"},
            {".jpgv", "video/jpeg"},
            {".sbml", "application/sbml+xml"},
            {".rdf", "application/rdf+xml"},
            {".ipfix", "application/ipfix"},
            {".mbox", "application/mbox"},
            {".shf", "application/shf+xml"},
            {".pls", "application/pls+xml"},
            {".vxml", "application/voicexml+xml"},
            {".atom, .xml", "application/atom+xml"},
            {".smi", "application/smil+xml"},
            {".mxf", "application/mxf"},
            {".rl", "application/resource-lists+xml"},
            {".rld", "application/resource-lists-diff+xml"},
            {".rs", "application/rls-services+xml"},
            {".davmount", "application/davmount+xml"},
            {".mscml", "application/mediaservercontrol+xml"},
            {".atomcat", "application/atomcat+xml"},
            {".atomsvc", "application/atomsvc+xml"},
            {".scq", "application/scvp-cv-request"},
            {".scs", "application/scvp-cv-response"},
            {".spq", "application/scvp-vp-request"},
            {".spp", "application/scvp-vp-response"},
            {".p8", "application/pkcs8"},
            {".xer", "application/patch-ops-error+xml"},
            {".dssc", "application/dssc+der"},
            {".xdssc", "application/dssc+xml"},
            {".ac", "application/pkix-attr-cert"},
            {".tfi", "application/thraud+xml"},
            {".tsd", "application/timestamped-data"},
            {".pskcxml", "application/pskc+xml"},
            {".tei", "application/tei+xml"},
            {".mads", "application/mads+xml"},
            {".mrcx", "application/marcxml+xml"},
            {".mets", "application/mets+xml"},
            {".mods", "application/mods+xml"},
            {".sru", "application/sru+xml"},
            {".cdmia", "application/cdmi-capability"},
            {".cdmic", "application/cdmi-container"},
            {".cdmid", "application/cdmi-domain"},
            {".cdmio", "application/cdmi-object"},
            {".cdmiq", "application/cdmi-queue"},
            {".rgb", "image/x-rgb"},
            {".movie", "video/x-sgi-movie"},
            {".aw", "application/applixware"},
            {".ccxml", "application/ccxml+xml,"},
            {".dtd", "application/xml-dtd"},
            {".mathml", "application/mathml+xml"},
            {".prf", "application/pics-rules"},
            {".rq", "application/sparql-query"},
            {".srx", "application/sparql-results+xml"},
            {".gram", "application/srgs"},
            {".grxml", "application/srgs+xml"},
            {".ssml", "application/ssml+xml"},
            {".wsdl", "application/wsdl+xml"},
            {".wspolicy", "application/wspolicy+xml"},
            {".wgt", "application/widget"},
            {".xhtml", "application/xhtml+xml"},
            {".xml", "application/xml"},
            {".xenc", "application/xenc+xml"},
            {".xop", "application/xop+xml"},
            {".xslt", "application/xslt+xml"},
            {".weba", "audio/webm"},
            {".webm", "video/webm"},
            {".cu", "application/cu-seeme"},
            {".3g2", "video/3gpp2"},
            {".3gp", "video/3gpp"},
            {".7z", "application/x-7z-compressed"},
            {".aac", "audio/x-aac"},
            {".abw", "application/x-abiword"},
            {".ace", "application/x-ace-compressed"},
            {".swf", "application/x-shockwave-flash"},
            {".dir", "application/x-director"},
            {".adp", "audio/adpcm"},
            {".asf", "video/x-ms-asf"},
            {".wm", "video/x-ms-wm"},
            {".wmv", "video/x-ms-wmv"},
            {".wmx", "video/x-ms-wmx"},
            {".wvx", "video/x-ms-wvx"},
            {".apk", "application/vnd.android.package-archive"},
            {".s", "text/x-asm"},
            {".aif", "audio/x-aiff"},
            {".aab", "application/x-authorware-bin"},
            {".aam", "application/x-authorware-map"},
            {".aas", "application/x-authorware-seg"},
            {".dxf", "image/vnd.dxf"},
            {".avi", "video/x-msvideo"},
            {".torrent", "application/x-bittorrent"},
            {".bmp", "image/bmp"},
            {".sh", "application/x-sh"},
            {".bz", "application/x-bzip"},
            {".bz2", "application/x-bzip2"},
            {".c", "text/x-c"},
            {".csh", "application/x-csh"},
            {".cml", "chemical/x-cml"},
            {".csml", "chemical/x-csml"},
            {".application", "application/x-ms-application"},
            {".clp", "application/x-msclip"},
            {".sub", "image/vnd.dvb.subtitle"},
            {".cgm", "image/cgm"},
            {".ice", "x-conference/x-cooltalk"},
            {".cmx", "image/x-cmx"},
            {".bcpio", "application/x-bcpio"},
            {".cpio", "application/x-cpio"},
            {".css", "text/css"},
            {".csv", "text/csv"},
            {".deb", "application/x-debian-package"},
            {".dwf", "model/vnd.dwf"},
            {".djvu", "image/vnd.djvu"},
            {".wad", "application/x-doom"},
            {".dvi", "application/x-dvi"},
            {".dwg", "image/vnd.dwg"},
            {".epub", "application/epub+zip"},
            {".ncx", "application/x-dtbncx+xml"},
            {".dtb", "application/x-dtbook+xml"},
            {".exe", "application/x-msdownload"},
            {".f4v", "video/x-f4v"},
            {".flv", "video/x-flv"},
            {".f", "text/x-fortran"},
            {".spl", "application/x-futuresplash"},
            {".g3", "image/g3fax"},
            {".gsf", "application/x-font-ghostscript"},
            {".bdf", "application/x-font-bdf"},
            {".gnumeric", "application/x-gnumeric"},
            {".gif", "image/gif"},
            {".h261", "video/h261"},
            {".h263", "video/h263"},
            {".h264", "video/h264"},
            {".hdf", "application/x-hdf"},
            {".html", "text/html"},
            {".ics", "text/calendar"},
            {".ico", "image/x-icon"},
            {".igs", "model/iges"},
            {".crd", "application/x-mscardfile"},
            {".jar", "application/java-archive"},
            {".java", "text/x-java-source,java"},
            {".class", "application/java-vm"},
            {".jnlp", "application/x-java-jnlp-file"},
            {".json", "application/json"},
            {".latex", "application/x-latex"},
            {".m3u8", "application/vnd.apple.mpegurl"},
            {".m3u", "audio/x-mpegurl"},
            {".m4v", "video/x-m4v"},
            {".fh", "image/x-freehand"},
            {".meta4", "application/metalink4+xml"},
            {".mdb", "application/x-msaccess"},
            {".mdi", "image/vnd.ms-modi"},
            {".mny", "application/x-msmoney"},
            {".pub", "application/x-mspublisher"},
            {".scd", "application/x-msschedule"},
            {".obd", "application/x-msbinder"},
            {".doc", "application/msword"},
            {".mid", "audio/midi"},
            {".prc", "application/x-mobipocket-ebook"},
            {".mp4", "video/mp4"},
            {".mp4a", "audio/mp4"},
            {".mpeg", "video/mpeg"},
            {".m21", "application/mp21"},
            {".mpga", "audio/mpeg"},
            {".mxml", "application/xv+xml"},
            {".nc", "application/x-netcdf"},
            {".pnm", "image/x-portable-anymap"},
            {".pbm", "image/x-portable-bitmap"},
            {".pgm", "image/x-portable-graymap"},
            {".ppm", "image/x-portable-pixmap"},
            {".n3", "text/n3"},
            {".ogx", "application/ogg"},
            {".oga", "audio/ogg"},
            {".ogv", "video/ogg"},
            {".opf", "application/oebps-package+xml"},
            {".sxc", "application/vnd.sun.xml.calc"},
            {".stc", "application/vnd.sun.xml.calc.template"},
            {".sxd", "application/vnd.sun.xml.draw"},
            {".std", "application/vnd.sun.xml.draw.template"},
            {".sxi", "application/vnd.sun.xml.impress"},
            {".sti", "application/vnd.sun.xml.impress.template"},
            {".sxm", "application/vnd.sun.xml.math"},
            {".sxw", "application/vnd.sun.xml.writer"},
            {".sxg", "application/vnd.sun.xml.writer.global"},
            {".stw", "application/vnd.sun.xml.writer.template"},
            {".p", "text/x-pascal"},
            {".sv4cpio", "application/x-sv4cpio"},
            {".sv4crc", "application/x-sv4crc"},
            {".pcx", "image/x-pcx"},
            {".psd", "image/vnd.adobe.photoshop"},
            {".pic", "image/x-pict"},
            {".chat", "application/x-chat"},
            {".pcf", "application/x-font-pcf"},
            {".pgn", "application/x-chess-pgn"},
            {".ai", "application/postscript"},
            {".pfa", "application/x-font-type1"},
            {".qt", "video/quicktime"},
            {".rar", "application/x-rar-compressed"},
            {".rsd", "application/rsd+xml"},
            {".ram", "audio/x-pn-realaudio"},
            {".rmp", "audio/x-pn-realaudio-plugin"},
            {".rtf", "application/rtf"},
            {".rtx", "text/richtext"},
            {".rss, .xml", "application/rss+xml"},
            {".snf", "application/x-font-snf"},
            {".etx", "text/x-setext"},
            {".sgml", "text/sgml"},
            {".shar", "application/x-shar"},
            {".xap", "application/x-silverlight-app"},
            {".sit", "application/x-stuffit"},
            {".sitx", "application/x-stuffitx"},
            {".au", "audio/basic"},
            {".svg", "image/svg+xml"},
            {".tar", "application/x-tar"},
            {".tcl", "application/x-tcl"},
            {".trm", "application/x-msterminal"},
            {".tex", "application/x-tex"},
            {".tfm", "application/x-tex-tfm"},
            {".texinfo", "application/x-texinfo"},
            {".txt", "text/plain"},
            {".tiff", "image/tiff"},
            {".t", "text/troff"},
            {".ttf", "application/x-font-ttf"},
            {".tsv", "text/tab-separated-values"},
            {".ttl", "text/turtle"},
            {".ustar", "application/x-ustar"},
            {".uu", "text/x-uuencode"},
            {".vcs", "text/x-vcalendar"},
            {".vcf", "text/x-vcard"},
            {".vcd", "application/x-cdlink"},
            {".wrl", "model/vrml"},
            {".wav", "audio/x-wav"},
            {".woff", "application/x-font-woff"},
            {".webp", "image/webp"},
            {".wma", "audio/x-ms-wma"},
            {".wmd", "application/x-ms-wmd"},
            {".wmz", "application/x-ms-wmz"},
            {".wmf", "application/x-msmetafile"},
            {".hlp", "application/winhlp"},
            {".wml", "text/vnd.wap.wml"},
            {".wmls", "text/vnd.wap.wmlscript"},
            {".wri", "application/x-mswrite"},
            {".xbm", "image/x-xbitmap"},
            {".xpm", "image/x-xpixmap"},
            {".xwd", "image/x-xwindowdump"},
            {".der", "application/x-x509-ca-cert"},
            {".xbap", "application/x-ms-xbap"},
            {".xdf", "application/xcap-diff+xml"},
            {".fig", "application/x-xfig"},
            {".xdp", "application/vnd.adobe.xdp+xml"},
            {".xfdf", "application/vnd.adobe.xfdf"},
            {".xpi", "application/x-xpinstall"},
            {".xyz", "chemical/x-xyz"},
            {".yang", "application/yang"},
            {".yin", "application/yin+xml"},
            {".zip", "application/zip"},
            {".mvb", "application/x-msmediaview"},
            {".wax", "audio/x-ms-wax"},
            {".xspf", "application/xspf+xml"},
            {".yaml", "text/yaml"},
            {".src", "application/x-wais-source"}
        };
    }
}
